version: "3"

services:
    api-randint:
        container_name: api-randint
        build: ./api-randint
        volumes: 
            - ./api-randint:/app
        ports:
            - "5000:5000"

    api-agenda:
        container_name: api-agenda
        build: ./api-agenda
        volumes: 
            - ./api-agenda:/app
        ports:
            - "8080:8080"
        depends_on:
            - database-pg

    database-pg:
        container_name: database-pg
        image: postgres
        restart: always
        environment: 
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: agenda
        volumes: 
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports: 
            - "5432:5432"
