version: "3"

services:
    database:
        container_name: postgres
        image: postgres
        restart: always
        environment: 
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: agenda
        volumes: 
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports: 
            - "5432:5432"
